---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCTpuEaFnb0cQeFlZB+g8MmkOcMwzhNHG82xXDwcaq9C7pRzAPI7D6jrWpYH4otV18YOCixtRz/cUaqzkN/82D65vWANa3EL+Fk6D0JgbODVRL+scMkqyTjuYVZ31DorIPkfPVtgQUZST+pGHAMU09Ts09X4FfPVdra7iagURvPyuQ0jZ4oSYLQc1thR2xQxL2piVrDsKOpDZSul1YC8MAMg/ikMcd7YtZsDjovcyEy25PxHhA/ANzx0XOTtXvBl7QK/au/1iXnAoR6bB/BEhT9OlT9HdQdGwLaUa5HS6cCHKEKB/gP0ctrHpISiyLnYa8IOsBNhywcG79HNbl0o5DDUrQ4fowTEWP/+wuKs/WS+fAXZXCDAHA6O+nCxJWr3EhTyAIFfv6Zk68e2pyc8pjSTY49NyQaYIFh/C+b4oSVDMVd0qztvJbKBYgLQakuA1JKFhkPQqZ9d2SynhgBiR2wNOh5zNbp15sIP5wubQpfEPnJvaeUeGaygYArEfsWCVmo4BrVc8K6WM9b3/fUSlJa+eOhypjExVqB40rrKqgfhECq/hsTZzoiv/dn2t+4YlH1S1QltFSzHNH8FUj3l0oBrB3IMqTghQoIkBMFWvVNcGAI1TFFi7M7xbhkZ7eyrtAppcTuQ4XxqVvPbR5A1rEIo9J/b9/v7jpYzYZanSjd+sE+JlO0X7bz7wXfgz11pMf1+g8eUPCDWw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque
