---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBCcuc5e5EJplIZKqRIURXBvVoLXxg3oHZcr7M44ciTICKZPdo4EtDuxoHyUfx16Ari7ujy7Sqem4WSiYOg+q4tXe1NmYlaEYNARzzomtc1NorvDBQtW8yIqIvfaY3DrNaWLKnlRbYZzhWIwvIPfBw0NnWP3E96raWi4Z8mFA2SlFQw0nPjRPqxXlzPG27syyCNJEpHsxtXUVCEN1DwVC+pd3hrwVmY60uNgLg28UUhzOgdWoSGJyaMycz8ubvmX12bu9OKZjFVc96MmfKbT9RTiQEVq6vL66dnqdYOF4K9vf1Qyj55ruaF/XfdC9z9ucSQj0bEyCBfEiCBmXRRcz6XkIbW+nj2DiUIKrIPfLIl0q0NYo5o0PzuFZjL8dhtqxDCiP7KHSLseyNNJzNvSwBXYaxsqNKIc1Znf3qToaYEsuzgLFT7ZH1utZGguZQGZkNeYbnknET/fg1urjsreu5VyMBLJoQLh20GIUzr5gWSrT7dxjdgQji1hSG5OcaoHT8qfLm6tbhpt0eOf73MaUpBc3hmlViTXO94wpjCUST5Y1bD3TRL2xtyGtqcMJ6zxUoCKp4L9i04HSMDY1XCESi06fl+WuhWrnxqaGOMEWiU7AYC6gTpal/Mv+7i4yhC0oTxuruOyB2gINFYFQqT88ZsovXBGWQrnBzgAfh1ImC28G7VZWPdJUPt/5D6I4qs7JHK4rQ1OtKUeg==
    DB_USER: AgDAWOTs3Q6DdNgwSI4zu/tEiPBVe8ULxXHuxMEbHaZhNuj9knxISkGMW+OO3A8mNf2HonWWuxs61cMlb06eyYeIi74rdYuqXvHBSR4MdN1ULHTL/n9eJi4A+6kvDjYW3rkYzZWWXoTB2/Q+NCqQLHIDKJ29xPqGK+aK0oUNXLwuLgWkJK7a7T+X5Gk1+9a9Su1Ub0xTUC+AfZDTf91MYmxZsqianU7bQSVWVad7W9rSTXeYh2EhfTz8YloGnnZ51vxS0OfuSIbonaQoQldYb5M1/CAgqa8Qf+ImjuzjBzYPlDCaxhpP51ta8PbSzrmLrj7aasatOyydalO4M4aZYMbnrnNm77U0cYELrNyN9i193dSgd1MsCsSV2o0mwndu75jISGHsb4cwW67s04c+R+ftEZr8umM57H78SmD6iVtMPxiysec3b21cP73mLzdoCtLzr4j1gYornMq4meDcl/RWNC8QA9rl2k4sP2BRNmnfy+YjZ9Fiv4e5dUPSTiJxM7drpaIUtAVvn708UxiogUMX7/5H0k8IHgPcPYC+XJiFOB7wlKyXN7WrhrBKzsbRGmttjnBrY+0V2p/SgJkepYYH3+J6VDFI/I7BUqgyKo/tllmtUQX9ocRA7+1CGvGRVHv/ggWmWzqAWlCW4xPz54xMTO02hryYhXcL7Rt+PmKyzEYPx2kGpwTBl2/rowfo+EWzdCa7eJO2dA==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
